contentColumnType: string
fieldGroup: c9cbaf89-ac8d-4f35-9217-a85381376c9a
handle: aboutUsImage
instructions: 'Image for About Us page.'
name: 'About Us Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:67bf9c86-03b7-4ff5-b70d-e122ed45dafb'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1a0d8658-95f6-46ad-9ec4-2587b0625c78'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
