contentColumnType: string(4800)
fieldGroup: c32665f2-7427-4547-8f98-3ea5ab6ce351
handle: description
instructions: 'General Description of the Package. Sell it up!'
name: Description
searchable: true
settings:
  byteLimit: null
  charLimit: 1200
  code: ''
  columnType: null
  initialRows: '4'
  multiline: '1'
  placeholder: Description...
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
