contentColumnType: string(400)
fieldGroup: c9cbaf89-ac8d-4f35-9217-a85381376c9a
handle: homePageHeroHeading
instructions: 'Hero heading for home page.'
name: 'Home Page Hero Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: 100
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
