contentColumnType: smallint(3)
fieldGroup: c32665f2-7427-4547-8f98-3ea5ab6ce351
handle: numberOfDays
instructions: 'How many days the package includes.'
name: 'Number of days'
searchable: false
settings:
  decimals: 0
  defaultValue: '1'
  max: '100'
  min: '0'
  prefix: ''
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
