fieldLayouts:
  152dd722-0f1c-4bdf-a9fa-4c6ba26abef7:
    tabs:
      -
        elements:
          -
            fieldUid: fb2962eb-b23b-42b1-8432-d585cd78db03
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 05a02c09-1689-4083-b65b-f4d32ac156cc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1e7c55ad-65ed-437c-9da3-faddd6efada9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c9536ce5-d995-4cef-8cd7-80902dd6e64b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: af6c8288-4157-4aaf-8a21-9cb8ad112a70
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bf96c18b-e40b-43ee-913b-906dc1582a92
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5cf56dbd-89ad-46de-b7f0-a8bec2a65ca8
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d4c9a67d-a455-401d-a03d-dbca68842d52
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8f1d2e86-8a19-4ca3-8eae-23c4216834b3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: af3bf102-70c0-459e-a1d2-7715e1c22eb6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: General
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
