enableVersioning: true
handle: aboutUsPage
name: 'About Us Page'
propagationMethod: all
siteSettings:
  43e35aab-41f0-411f-86e3-a59638467252:
    enabledByDefault: true
    hasUrls: true
    template: pages/about-us
    uriFormat: about-us
type: single
