enableVersioning: true
handle: toursPackages
name: 'Tours & Packages'
propagationMethod: all
siteSettings:
  43e35aab-41f0-411f-86e3-a59638467252:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'tours-packages/{slug}'
type: channel
